---

- name: HDFS HOSTS | Configure Hosts file with master node
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item].ip }} hdfs-master-{{ item }}.{{ default_dns_domain }}"
    state: present
  with_items: "{{ groups['hdfs_master'] }}"

- name: HDFS HOSTS | Configure Hosts file with slave node
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item].ip }} hdfs-slave-{{ item }}.{{ default_dns_domain }}"
    state: present
  with_items: "{{ groups['hdfs_slave'] }}"
